{"name": "ContactUS Form", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div[1]/div/div/div/main/article/div/div/section[2]/div/div[1]/div/div/div/div/div/div/div[1]/p[1]\"}\n  (Session info: chrome=115.0.5790.171); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00EAA813+48355]\n\t(No symbol) [0x00E3C4B1]\n\t(No symbol) [0x00D45358]\n\t(No symbol) [0x00D709A5]\n\t(No symbol) [0x00D70B3B]\n\t(No symbol) [0x00D9E232]\n\t(No symbol) [0x00D8A784]\n\t(No symbol) [0x00D9C922]\n\t(No symbol) [0x00D8A536]\n\t(No symbol) [0x00D682DC]\n\t(No symbol) [0x00D693DD]\n\tGetHandleVerifier [0x0110AABD+2539405]\n\tGetHandleVerifier [0x0114A78F+2800735]\n\tGetHandleVerifier [0x0114456C+2775612]\n\tGetHandleVerifier [0x00F351E0+616112]\n\t(No symbol) [0x00E45F8C]\n\t(No symbol) [0x00E42328]\n\t(No symbol) [0x00E4240B]\n\t(No symbol) [0x00E34FF7]\n\tBaseThreadInitThunk [0x75EF7D59+25]\n\tRtlInitializeExceptionChain [0x770BB79B+107]\n\tRtlClearBits [0x770BB71F+191]\n\n", "trace": "  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contactussteps.py\", line 25, in step_impl\n    text = context.driver.find_element(By.XPATH, \"/html/body/div[1]/div/div/div/main/article/div/div/section[2]/div/div[1]/div/div/div/div/div/div/div[1]/p[1]\").text\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch chrome browser", "status": "passed", "start": 1691758639326, "stop": 1691758641596}, {"name": "When Navigate to contact us page", "status": "passed", "start": 1691758641596, "stop": 1691758650168}, {"name": "And Phen Enter  fullname \"William Obese\", second \"williamgyau248@gmail.com\", phone\"0208033577\", message \"test\"", "status": "passed", "start": 1691758650168, "stop": 1691758650617}, {"name": "Then Click Submit", "status": "passed", "start": 1691758650617, "stop": 1691758650711}, {"name": "Then Message Sent", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div[1]/div/div/div/main/article/div/div/section[2]/div/div[1]/div/div/div/div/div/div/div[1]/p[1]\"}\n  (Session info: chrome=115.0.5790.171); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00EAA813+48355]\n\t(No symbol) [0x00E3C4B1]\n\t(No symbol) [0x00D45358]\n\t(No symbol) [0x00D709A5]\n\t(No symbol) [0x00D70B3B]\n\t(No symbol) [0x00D9E232]\n\t(No symbol) [0x00D8A784]\n\t(No symbol) [0x00D9C922]\n\t(No symbol) [0x00D8A536]\n\t(No symbol) [0x00D682DC]\n\t(No symbol) [0x00D693DD]\n\tGetHandleVerifier [0x0110AABD+2539405]\n\tGetHandleVerifier [0x0114A78F+2800735]\n\tGetHandleVerifier [0x0114456C+2775612]\n\tGetHandleVerifier [0x00F351E0+616112]\n\t(No symbol) [0x00E45F8C]\n\t(No symbol) [0x00E42328]\n\t(No symbol) [0x00E4240B]\n\t(No symbol) [0x00E34FF7]\n\tBaseThreadInitThunk [0x75EF7D59+25]\n\tRtlInitializeExceptionChain [0x770BB79B+107]\n\tRtlClearBits [0x770BB71F+191]\n\n", "trace": "  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contactussteps.py\", line 25, in step_impl\n    text = context.driver.find_element(By.XPATH, \"/html/body/div[1]/div/div/div/main/article/div/div/section[2]/div/div[1]/div/div/div/div/div/div/div[1]/p[1]\").text\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691758650711, "stop": 1691758650737}], "start": 1691758639323, "stop": 1691758650738, "uuid": "dc1a1861-6120-4eff-a321-b1304b48e1d3", "historyId": "60178240d8ea841271f3fd52e747ee37", "fullName": "ContactUs: ContactUS Form", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "ContactUs"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}